---
- name: Enable nginx repo.
  become: true
  service:
    - name: nginx
      enabled: yes
  when: nginx_yum_repo_enabled | bool

- name: Ensure nginx is installed.
  package:
    name: "{{ nginx_package_name }}"
    state: present
