---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  become: true
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: latest
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes
        
   

- name: update LB server
  hosts: lb
  become: true
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: install nginx
      apt:
        name: nginx
        state: latest
