---
- hosts: all
  become: true

#- name: Include dynamic variables 
#  import_playbook: ../static-assignments/common.yml 
  
- name: Include  
  import_playbook: ../dynamic-assignments/env-vars.yml
  
#- name: import webservers file
#  import_playbook: ../static-assignments/webservers.yml

- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required