---
- hosts: hosts

- name: Include dynamic variables 
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: Loadbalancers assignment
  hosts: lb
    - import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required 
